# Secrets for Sudan Digital Identity System
# NOTE: In production, these should be managed by a secret management system
apiVersion: v1
kind: Secret
metadata:
  name: sudan-identity-secrets
  namespace: sudan-identity
  labels:
    app: sudan-digital-identity
    component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  POSTGRES_USER: c3VkYW5fYWRtaW4=  # sudan_admin
  POSTGRES_PASSWORD: U3VkYW5EQjIwMjQh  # SudanDB2024!
  
  # Redis password
  REDIS_PASSWORD: c3VkYW5yZWRpczIwMjQ=  # sudanredis2024
  
  # JWT Secret for authentication
  JWT_SECRET: U3VkYW5EaWdpdGFsSWRlbnRpdHlTZWNyZXQyMDI0IQ==  # SudanDigitalIdentitySecret2024!
  
  # Encryption keys for biometric data
  BIOMETRIC_ENCRYPTION_KEY: QmlvbWV0cmljS2V5MjAyNFN1ZGFuIQ==  # BiometricKey2024Sudan!
  
  # Blockchain network credentials
  FABRIC_CA_ADMIN_PASSWORD: RmFicmljQWRtaW4yMDI0IQ==  # FabricAdmin2024!
  
  # API Keys for external services
  MAPS_API_KEY: c3VkYW5fbWFwc19hcGlfa2V5XzIwMjQ=  # sudan_maps_api_key_2024
  SMS_API_KEY: c3VkYW5fc21zX2FwaV9rZXlfMjAyNA==  # sudan_sms_api_key_2024
  
  # MinIO credentials for object storage
  MINIO_ROOT_USER: c3VkYW5hZG1pbg==  # sudanadmin
  MINIO_ROOT_PASSWORD: U3VkYW5NaW5pbzIwMjQh  # SudanMinio2024!

---
# TLS Secret for HTTPS
apiVersion: v1
kind: Secret
metadata:
  name: sudan-identity-tls
  namespace: sudan-identity
  labels:
    app: sudan-digital-identity
    component: tls
type: kubernetes.io/tls
data:
  # These should be replaced with actual certificates
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t

---
# Docker Registry Secret for pulling images
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: sudan-identity
  labels:
    app: sudan-digital-identity
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoic3VkYW4tZ292IiwicGFzc3dvcmQiOiJnaHBfWW91ckFjdHVhbEdpdEh1YlRva2VuSGVyZSIsImF1dGgiOiJjM1ZrWVc0dFoyOTJPbWRvY0Y5WmIzVnlRV04wZFdGc1IybDBTSFZpVkc5clpXNUlaWEpsIn19fQ==